name: 'Update Rules'

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:
  schedule:
    - cron: "0 16 1/7 * *"
  push:
    branches:
      - custom-rules
      - main
    paths:
        - '*.list'
        - '.github/workflows/**.yml'

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.RELEASE_HUB_SECRET }}
        submodules: true

    # Update references
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git checkout main
        #update ZJU and general rules
        git submodule update --remote --recursive
        echo "ZJU and general rules updated"
        #update custom rules
        a=$(git show origin/custom-rules:)
        b=${a:27}
        b=${b//${a:26:1}/ }
        while [ ${#b} -gt 0 ]; do
          n=$(expr match "$b" "[^ ]*");
          if [ ${b:0:n} != ".github/" ]; then
            git show origin/custom-rules:${b:0:n} > rules/custom-rules/${b:0:n};
          fi
          b=${b:n+1};
        done
        echo "custom rules updated"


    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.RELEASE_HUB_SECRET }}@github.com/${{ github.repository }}
        git add -A
        git commit -am "Auto updated rules" && git push || echo "No changes to commit"
